// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lndwvicwlswmpnhkcgot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuZHd2aWN3bHN3bXBuaGtjZ290Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDA3MTQsImV4cCI6MjA3MTg3NjcxNH0.9zp7eaxRMtHlFUez8u2bTgiPndnz95joSVUTtkkaQ9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});