// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nclzznsghwhgjlbmmyjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jbHp6bnNnaHdoZ2psYm1teWp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMzUxMDQsImV4cCI6MjA2ODcxMTEwNH0.nIq9PzK77X0To-_mE15ufplcbJx7v5A6moM2Yeu8GFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});